[functions]
  directory = "api"

[build]
  edge_functions = "api/_edge"

[[edge_functions]]
  path = "/api/dummy"
  function = "dummy"

[[edge_functions]]
  path = "/api/suggest"
  function = "suggest"

[[edge_functions]]
  path = "/api/search"
  function = "search"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "lighthouse.html"