[build]
  edge_functions = "_functions/_edge"

[[edge_functions]]
  path = "/api/suggest"
  function = "suggest"

[[edge_functions]]
  path = "/api/search"
  function = "search"

[[edge_functions]]
  path = "/api/comments"
  function = "comments"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "lighthouse.html"